/*!
* name : dlxSoal jQuery Plugin
* author : Chyno Deluxe
* version : 1.0.0
*
* Penjelasan dan beberapa kalimat diubah kedalam bahasa Indonesia oleh saya (Moccatory)
* Penambahan score dihasil akhir, agar user yang mengerjakan Soal tau berapa nilai yang didapat
*
* copyright (c) 2016 Chyno Deluxe - http://www.chynodeluxe.com
* license MIT
*/(function($){"use strict";$.dlxSoal=function(element,options){var plugin=this,$element=$(element),_element_id=$element.attr('id'),_element='#'+_element_id,question_index=0,SoalData=options.SoalData,questions=null,questionCount=null,defaults={questionCount_text:"Pertanyaan ke %current_index dari %totalQuestions pertanyaan",backButton_text:"Pertanyaan sebelumnya",nextButton_text:"Pertanyaan selanjutnya",completeButton_text:"Finish Soal",viewResultsButton_text:"Lihat Hasil",resultsHeader_text:"Ini yang tadi kamu kerjakan.",SoalScore_text:"Kamu menjawab %totalScore dari %totalQuestions pertanyaan dengan benar.",SoalScoreMessage_text:"",SoalScoreRank_text:{a:"Nilai Sempurna!",b:"Kerja Bagus!",c:"Setidaknya kamu enggak gagal",d:"Kamu harus belajar lebih giat",f:"Kamu serius waktu ngerjain Soal ini?",g:"Sedikit lagi.."},show_QuestionCount:true,showBackButton:true,showRadioButtons:true,showScoreRank:true,showScoreMessage:true,showViewResultsButton:true,randomizeQuestions:true,randomizeAnswers:true,},class_disabled="disabled",class_SoalQuestions="SoalQuestions",class_showQuestion="showQuestion",class_questionCount="questionCount",class_questionTitle="questionTitle",class_questionAnswers="questionAnswers",class_selectedAnswer="selectedAnswer",class_SoalControls="SoalControls",class_ctrlPreviousButton="ctrlPrev",class_ctrlNextButton="ctrlNext",class_ctrlCompleteButton="ctrlDone",class_SoalResults="SoalResults",class_SoalScoreRank="SoalScoreRank",class_SoalScore="SoalScore",class_SoalScoreMessage="SoalScoreMessage",class_viewResultsButton="viewResults",class_showingResults="showingResults",_questions=" ."+class_SoalQuestions,_question=_questions+' > li',_answers=" ."+class_questionAnswers,_controls=" ."+class_SoalControls,_ctrlPreviousButton=" ."+class_ctrlPreviousButton,_ctrlNextButton=" ."+class_ctrlNextButton,_ctrlCompleteButton=" ."+class_ctrlCompleteButton,_results=" ."+class_SoalResults,_viewResultsButton=" ."+class_viewResultsButton,_showingResults=" ."+_showingResults,_SoalQuestions=_element+_question,_Soal_answer=_element+_answers+' li',_SoalCtrls=_element+_controls,_SoalCtrlPreviousButton=_element+_ctrlPreviousButton,_SoalCtrlNextButton=_element+_ctrlNextButton,_SoalCompleteButton=_element+_ctrlCompleteButton,_SoalViewResultsButton=_element+_viewResultsButton,_SoalResults=_element+_results;plugin.config=$.extend(defaults,options);plugin.method={buildSoal:function(data){var _SoalHTML;SoalData=data;questions=plugin.config.randomizeQuestions?plugin.method.randomizeArray(SoalData.questions):SoalData.questions;questionCount=questions.length;if(!$element.hasClass("Soal")){$element.addClass("Soal");}
_SoalHTML='<ul class="'+class_SoalQuestions+'">';$.each(questions,function(q){var question=questions[q];question.options=plugin.config.randomizeAnswers?plugin.method.randomizeArray(question.options):question.options;_SoalHTML+='<li';_SoalHTML+=(q===0?' class="'+class_showQuestion+'">':'>');if(plugin.config.show_QuestionCount){_SoalHTML+='<span class="'+class_questionCount+'">';_SoalHTML+=plugin.config.questionCount_text.replace('%current_index',q+1).replace('%totalQuestions',questionCount);_SoalHTML+='</span>';}
_SoalHTML+='<h2 class="'+class_questionTitle+'">';_SoalHTML+=question.q;_SoalHTML+='</h2>';_SoalHTML+='<ul class="'+class_questionAnswers+'">';$.each(question.options,function(a){var _input_name=_element_id+'-q'+(q+1),_input_id=_input_name+'-a'+(a+1);_SoalHTML+='<li>';_SoalHTML+='<label for="'+_input_id+'">';_SoalHTML+='<input ';_SoalHTML+=(plugin.config.showRadioButtons?'':'class="hidden" ');_SoalHTML+='type="radio" name="';_SoalHTML+=_input_name+'"';_SoalHTML+=' id="'+_input_id+'"';_SoalHTML+=' value="'+question.options[a]+'">';_SoalHTML+=question.options[a];_SoalHTML+='</label>';_SoalHTML+='</li>';});_SoalHTML+='</ul>';_SoalHTML+='</li>';q+=1;});_SoalHTML+='</ul>';_SoalHTML+='<div class="'+class_SoalControls+'">';if(plugin.config.showBackButton){_SoalHTML+='<button class="'+class_ctrlPreviousButton+'">';_SoalHTML+=plugin.config.backButton_text+'</button>';}
_SoalHTML+='<button class="'+class_ctrlNextButton+' '+class_disabled+'">';_SoalHTML+=plugin.config.nextButton_text+'</button>';_SoalHTML+='<button class="'+class_ctrlCompleteButton+' '+class_disabled+'">';_SoalHTML+=plugin.config.completeButton_text+'</button>';_SoalHTML+='</div>';$element.append(_SoalHTML);plugin.events.init();},randomizeArray:function(array){var m=array.length,t,i;while(m){i=Math.floor(Math.random()*m--);t=array[m];array[m]=array[i];array[i]=t;}
return array;},buildSoalResults:function(){var resultsHTML='',correctAnswerCount=0,totalScore;function _checkAnswers(){$.each(questions,function(index){questions[index].answerCorrect=questions[index].selected===questions[index].a?true:false;if(questions[index].answerCorrect){correctAnswerCount+=1;}else{correctAnswerCount=correctAnswerCount;}});totalScore=(correctAnswerCount/questionCount)*100;}
_checkAnswers();resultsHTML+='<div class="'+class_SoalResults+'">';resultsHTML+='<h1 class="'+class_SoalScoreRank+'">';if(totalScore==100){resultsHTML+=totalScore+" - "+plugin.config.SoalScoreRank_text.a;}else if(totalScore>80){resultsHTML+=totalScore+" - "+plugin.config.SoalScoreRank_text.g;}else if(totalScore>60){resultsHTML+=totalScore+" - "+plugin.config.SoalScoreRank_text.b;}else if(totalScore>40){resultsHTML+=totalScore+" - "+plugin.config.SoalScoreRank_text.c;}else if(totalScore>20){resultsHTML+=totalScore+" - "+plugin.config.SoalScoreRank_text.d;}else{resultsHTML+=totalScore+" - "+plugin.config.SoalScoreRank_text.f;}
resultsHTML+='</h1>';resultsHTML+='<p class="'+class_SoalScore+'">';resultsHTML+=plugin.config.SoalScore_text.replace('%totalScore',correctAnswerCount).replace('%totalQuestions',questionCount);resultsHTML+='</p>';if(plugin.config.showScoreMessage){resultsHTML+='<p class="'+class_SoalScoreMessage+'">';resultsHTML+=plugin.config.SoalScoreMessage_text;resultsHTML+='</p>';}
if(plugin.config.showViewResultsButton){resultsHTML+='<button class="'+class_viewResultsButton+'">';resultsHTML+=plugin.config.viewResultsButton_text;resultsHTML+='</button>';}
$element.append(resultsHTML);if(plugin.config.showViewResultsButton){plugin.events.resultsButton();}}};plugin.events={init:function(){this.controls.init();this.answerQuestion();this.checkQuestion();},controls:{DOM:function(){this.plugin=plugin.events;this.questionCount=questionCount-1;this.$previous=$(_SoalCtrlPreviousButton);this.$next=$(_SoalCtrlNextButton);this.$complete=$(_SoalCompleteButton);this.$buttons=this.$previous.add(this.$next).add(this.$complete);},init:function(){this.DOM();var $buttons=this.$buttons,_this=this;$buttons.on('click',function(){var $button=$(this);if(_this.isNotDisabled($button)){switch($button.attr('class')){case class_ctrlPreviousButton:_this.plugin.previousQuestion();break;case class_ctrlNextButton:_this.plugin.nextQuestion();break;case class_ctrlCompleteButton:$(_element+' '+_questions).add(_SoalCtrls).remove();plugin.method.buildSoalResults();break;}}});},isNotDisabled:function(button){return!button.hasClass(class_disabled)?true:false;},resetDisabled:function(){var totalAnswered=0;switch(question_index){case 0:this.$previous.addClass(class_disabled);this.$complete.hide();this.$next.show();break;case this.questionCount:this.$next.addClass(class_disabled).hide();this.$previous.removeClass(class_disabled);this.$complete.show();break;default:this.$previous.removeClass(class_disabled);this.$next.show();this.$complete.hide();break;}
this.$next=questions[question_index].selected!==undefined?this.$next.removeClass(class_disabled):this.$next.addClass(class_disabled);$.each(questions,function(i){totalAnswered=questions[i].selected?totalAnswered+=1:totalAnswered=totalAnswered;});if(totalAnswered===questionCount){this.$complete.removeClass(class_disabled);}}},nextQuestion:function(){question_index+=1;this.checkQuestion();},previousQuestion:function(){question_index-=1;this.checkQuestion();},checkQuestion:function(){this.controls.resetDisabled();$(_SoalQuestions).removeClass(class_showQuestion);$($(_SoalQuestions)[question_index]).addClass(class_showQuestion);},answerQuestion:function(){function resetAnswerGroup(input){var _grpName=$('input:radio[name="'+input.prop("name")+'"]'),_inputParent=_grpName.parent().parent();_inputParent.removeClass(class_selectedAnswer);}
$(_Soal_answer+' input').on('click',function(e){var _$answer=$(this),_answerParent=_$answer.parent().parent();resetAnswerGroup(_$answer);_answerParent.addClass(class_selectedAnswer);questions[question_index].selected=_$answer.val();plugin.events.checkQuestion();});},resultsButton:function(){$(_SoalViewResultsButton).on('click',function(){var resultsHTML;$(_SoalViewResultsButton).remove();resultsHTML='<h2>'+plugin.config.resultsHeader_text+'</h2>';resultsHTML+='<ul class="'+class_showingResults+'">';$.each(questions,function(index){resultsHTML+='<li class="';resultsHTML+=questions[index].answerCorrect?'answeredCorrect':'answeredWrong';resultsHTML+='">';resultsHTML+='<h3 class="questionTitle">';resultsHTML+=(index+1)+". "+questions[index].q;resultsHTML+='</h3>';resultsHTML+='<p>';if(!questions[index].answerCorrect){resultsHTML+='<strong>Jawabanmu: </strong>';resultsHTML+=questions[index].selected+'<br>';}
resultsHTML+='<strong>Jawaban yang benar: </strong>';resultsHTML+=questions[index].a+'<br>';resultsHTML+='</p>';resultsHTML+='</li>';});resultsHTML+='</ul>';$(_SoalResults).append(resultsHTML);});}};if(SoalData){if(typeof SoalData==="string"){$.getJSON(SoalData).then(function(data){plugin.method.buildSoal(data);});}else if(typeof options.SoalData==="object"){plugin.method.buildSoal(SoalData);}else{SoalData=null;throw "Error: Check SoalData for - "+_element;}}};$.fn.dlxSoal=function(options){return this.each(function(){var plugin=new $.dlxSoal(this,options);});};}(jQuery));